Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.timer.server.gcTimer_ServerPlugin
Client Main: com.growcontrol.plugins.timer.client.gcTimer_ClientPlugin
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
