Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.mqtt.server.gcMqttPlugin_Server
Client Main: com.growcontrol.plugins.mqtt.client.gcMqttPlugin_Client
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
