Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.mqtt.server.gcMqtt_ServerPlugin
Client Main: com.growcontrol.plugins.mqtt.client.gcMqtt_ClientPlugin
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
