Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.button.server.gcButton_ServerPlugin
Client Main: com.growcontrol.plugins.button.client.gcButton_ClientPlugin
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
