Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.button.server.gcButtonPlugin_Server
Client Main: com.growcontrol.plugins.button.client.gcButtonPlugin_Client
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
