Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.sequencer.server.gcSequencerPlugin_Server
Client Main: com.growcontrol.plugins.sequencer.client.gcSequencerPlugin_Client
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
