Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.climate.server.gcClimate_ServerPlugin
Client Main: com.growcontrol.plugins.climate.client.gcClimate_ClientPlugin
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
