Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.arduino.server.gcArduino_ServerPlugin
Client Main: com.growcontrol.plugins.arduino.client.gcArduino_ClientPlugin
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
