Plugin Name: ${project.name}
Plugin Version: ${project.version}
Commit: ${git.commit.id}
Server Main: com.growcontrol.plugins.pi.server.gcPiPlugin_Server
Client Main: com.growcontrol.plugins.pi.client.gcPiPlugin_Client
Author: lorenzop
Website: ${project.url}
Depend: []
SoftDepend: []
